In [1]:
from pyspark.sql import SparkSession

# Create a spark session (which will run spark jobs)
spark = (
    SparkSession.builder.appName("MAST30034 Tutorial 1")
    .config("spark.sql.repl.eagerEval.enabled", True) 
    .config("spark.sql.parquet.cacheMetadata", "true")
    .config("spark.sql.session.timeZone", "Etc/UTC")
    .getOrCreate()
)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/09/18 17:46:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/09/18 17:46:53 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/09/18 17:46:53 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
26/09/18 17:46:53 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.

In [2]:
# Reading in the external datasets 
from urllib.request import urlretrieve
import os

# these are the ABS allocation files that will help us join postcode to SA2 via mesh block
# source: https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs/edition-3-july-2021-june-2026/access-and-downloads/allocation-files
ABS_FILES = {
    "MB_2021_AUST.xlsx": "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs/edition-3-july-2021-june-2026/access-and-downloads/allocation-files/MB_2021_AUST.xlsx",
    "POA_2021_AUST.xlsx": "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs/edition-3-july-2021-june-2026/access-and-downloads/allocation-files/POA_2021_AUST.xlsx",
}

output_relative_dir = '../../data/'

# data output directory is
abs_output_dir = output_relative_dir + 'raw_abs'
if not os.path.exists(abs_output_dir):
    os.makedirs(abs_output_dir)

for filename, url in ABS_FILES.items():
    output_path = f"{abs_output_dir}/{filename}"

    # Checks if the files have already been downloaded, skip if we've already downloaded it, 
    # every time the notebook is re-run for reproducibility checks
    if os.path.exists(output_path):
        print(f"Already downloaded: {filename}")
        continue

    print(f"Downloading {filename}...")
    urlretrieve(url, output_path)
    print(f"Completed {filename}")

Already downloaded: MB_2021_AUST.xlsx
Already downloaded: POA_2021_AUST.xlsx

In [3]:
import pandas as pd
excel_path_mb = f"{abs_output_dir}/MB_2021_AUST.xlsx"
pd.ExcelFile(excel_path_mb).sheet_names 

excel_path_poa = f"{abs_output_dir}/POA_2021_AUST.xlsx"
pd.ExcelFile(excel_path_poa).sheet_names

['POA_2021_AUST']

In [4]:
mb_df = pd.read_excel(excel_path_mb, sheet_name='MB_2021_AUST')
mb_df.head()

,MB_CODE_2021,MB_CATEGORY_2021,CHANGE_FLAG_2021,CHANGE_LABEL_2021,SA1_CODE_2021,SA2_CODE_2021,SA2_NAME_2021,SA3_CODE_2021,SA3_NAME_2021,SA4_CODE_2021,SA4_NAME_2021,GCCSA_CODE_2021,GCCSA_NAME_2021,STATE_CODE_2021,STATE_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
0,10000010000,Residential,0,No change,10901117207,109011172,Albury - East,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0209,http://linked.data.gov.au/dataset/asgsed3/MB/1...
1,10000021000,Commercial,0,No change,10901117612,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0829,http://linked.data.gov.au/dataset/asgsed3/MB/1...
2,10000022000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0388,http://linked.data.gov.au/dataset/asgsed3/MB/1...
3,10000023000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0254,http://linked.data.gov.au/dataset/asgsed3/MB/1...
4,10000024000,Residential,0,No change,10901117613,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0376,http://linked.data.gov.au/dataset/asgsed3/MB/1...

In [5]:

poa_df = pd.read_excel(excel_path_poa, sheet_name='POA_2021_AUST')
poa_df.head()

,MB_CODE_2021,POA_CODE_2021,POA_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
0,70034860000,0800,0800,AUS,Australia,0.0434,http://linked.data.gov.au/dataset/asgsed3/MB/7...
1,73861000000,0800,0800,AUS,Australia,0.0218,http://linked.data.gov.au/dataset/asgsed3/MB/7...
2,70016404900,0800,0800,AUS,Australia,0.0877,http://linked.data.gov.au/dataset/asgsed3/MB/7...
3,70016404800,0800,0800,AUS,Australia,0.0419,http://linked.data.gov.au/dataset/asgsed3/MB/7...
4,70016404700,0800,0800,AUS,Australia,0.0931,http://linked.data.gov.au/dataset/asgsed3/MB/7...

In [6]:
# Explore dataset, missing values, data types
print("MB_2021 dataset shape", mb_df.shape)
print(mb_df.dtypes)

print("")
print(mb_df.isna().sum())
mb_df.head()

MB_2021 dataset shape (368286, 19)
MB_CODE_2021           object
MB_CATEGORY_2021       object
CHANGE_FLAG_2021        int64
CHANGE_LABEL_2021      object
SA1_CODE_2021          object
SA2_CODE_2021          object
SA2_NAME_2021          object
SA3_CODE_2021          object
SA3_NAME_2021          object
SA4_CODE_2021          object
SA4_NAME_2021          object
GCCSA_CODE_2021        object
GCCSA_NAME_2021        object
STATE_CODE_2021        object
STATE_NAME_2021        object
AUS_CODE_2021          object
AUS_NAME_2021          object
AREA_ALBERS_SQKM      float64
ASGS_LOCI_URI_2021     object
dtype: object

MB_CODE_2021            0
MB_CATEGORY_2021        0
CHANGE_FLAG_2021        0
CHANGE_LABEL_2021       0
SA1_CODE_2021           0
SA2_CODE_2021           0
SA2_NAME_2021           0
SA3_CODE_2021           0
SA3_NAME_2021           0
SA4_CODE_2021           0
SA4_NAME_2021           0
GCCSA_CODE_2021         0
GCCSA_NAME_2021         0
STATE_CODE_2021         0
STATE_NAME_2021         0
AUS_CODE_2021           0
AUS_NAME_2021           0
AREA_ALBERS_SQKM      114
ASGS_LOCI_URI_2021      0
dtype: int64

,MB_CODE_2021,MB_CATEGORY_2021,CHANGE_FLAG_2021,CHANGE_LABEL_2021,SA1_CODE_2021,SA2_CODE_2021,SA2_NAME_2021,SA3_CODE_2021,SA3_NAME_2021,SA4_CODE_2021,SA4_NAME_2021,GCCSA_CODE_2021,GCCSA_NAME_2021,STATE_CODE_2021,STATE_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
0,10000010000,Residential,0,No change,10901117207,109011172,Albury - East,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0209,http://linked.data.gov.au/dataset/asgsed3/MB/1...
1,10000021000,Commercial,0,No change,10901117612,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0829,http://linked.data.gov.au/dataset/asgsed3/MB/1...
2,10000022000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0388,http://linked.data.gov.au/dataset/asgsed3/MB/1...
3,10000023000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0254,http://linked.data.gov.au/dataset/asgsed3/MB/1...
4,10000024000,Residential,0,No change,10901117613,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0376,http://linked.data.gov.au/dataset/asgsed3/MB/1...

In [7]:
# Explore dataset, missing values, data types
print("POA_2021 dataset shape", poa_df.shape)
print(poa_df.dtypes)

print("")
print(poa_df.isna().sum())
poa_df.head()

POA_2021 dataset shape (368286, 7)
MB_CODE_2021           object
POA_CODE_2021          object
POA_NAME_2021          object
AUS_CODE_2021          object
AUS_NAME_2021          object
AREA_ALBERS_SQKM      float64
ASGS_LOCI_URI_2021     object
dtype: object

MB_CODE_2021            0
POA_CODE_2021           0
POA_NAME_2021           0
AUS_CODE_2021           0
AUS_NAME_2021           0
AREA_ALBERS_SQKM      114
ASGS_LOCI_URI_2021      0
dtype: int64

,MB_CODE_2021,POA_CODE_2021,POA_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
0,70034860000,0800,0800,AUS,Australia,0.0434,http://linked.data.gov.au/dataset/asgsed3/MB/7...
1,73861000000,0800,0800,AUS,Australia,0.0218,http://linked.data.gov.au/dataset/asgsed3/MB/7...
2,70016404900,0800,0800,AUS,Australia,0.0877,http://linked.data.gov.au/dataset/asgsed3/MB/7...
3,70016404800,0800,0800,AUS,Australia,0.0419,http://linked.data.gov.au/dataset/asgsed3/MB/7...
4,70016404700,0800,0800,AUS,Australia,0.0931,http://linked.data.gov.au/dataset/asgsed3/MB/7...

In [8]:
# Merging the two datasets on "MB_CODE_2021"
mb_poa_merged = mb_df.merge(
    poa_df,
    on='MB_CODE_2021',
    how='outer',
    indicator=True
)

print(mb_poa_merged['_merge'].value_counts())
print("Merged dataset shape: ", mb_poa_merged.shape)
print(mb_poa_merged.dtypes)
mb_poa_merged.head()

_merge
both          368286
left_only          0
right_only         0
Name: count, dtype: int64
Merged dataset shape:  (368286, 26)
MB_CODE_2021              object
MB_CATEGORY_2021          object
CHANGE_FLAG_2021           int64
CHANGE_LABEL_2021         object
SA1_CODE_2021             object
SA2_CODE_2021             object
SA2_NAME_2021             object
SA3_CODE_2021             object
SA3_NAME_2021             object
SA4_CODE_2021             object
SA4_NAME_2021             object
GCCSA_CODE_2021           object
GCCSA_NAME_2021           object
STATE_CODE_2021           object
STATE_NAME_2021           object
AUS_CODE_2021_x           object
AUS_NAME_2021_x           object
AREA_ALBERS_SQKM_x       float64
ASGS_LOCI_URI_2021_x      object
POA_CODE_2021             object
POA_NAME_2021             object
AUS_CODE_2021_y           object
AUS_NAME_2021_y           object
AREA_ALBERS_SQKM_y       float64
ASGS_LOCI_URI_2021_y      object
_merge                  category
dtype: object

,MB_CODE_2021,MB_CATEGORY_2021,CHANGE_FLAG_2021,CHANGE_LABEL_2021,SA1_CODE_2021,SA2_CODE_2021,SA2_NAME_2021,SA3_CODE_2021,SA3_NAME_2021,SA4_CODE_2021,...,AUS_NAME_2021_x,AREA_ALBERS_SQKM_x,ASGS_LOCI_URI_2021_x,POA_CODE_2021,POA_NAME_2021,AUS_CODE_2021_y,AUS_NAME_2021_y,AREA_ALBERS_SQKM_y,ASGS_LOCI_URI_2021_y,_merge
0,10000009499,NOUSUALRESIDENCE,0,No change,19999949999,199999499,No usual address (NSW),19999,No usual address (NSW),199,...,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/1...,9494,No usual address (Aust.),AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/1...,both
1,10000010000,Residential,0,No change,10901117207,109011172,Albury - East,10901,Albury,109,...,Australia,0.0209,http://linked.data.gov.au/dataset/asgsed3/MB/1...,2640,2640,AUS,Australia,0.0209,http://linked.data.gov.au/dataset/asgsed3/MB/1...,both
2,10000021000,Commercial,0,No change,10901117612,109011176,Lavington,10901,Albury,109,...,Australia,0.0829,http://linked.data.gov.au/dataset/asgsed3/MB/1...,2641,2641,AUS,Australia,0.0829,http://linked.data.gov.au/dataset/asgsed3/MB/1...,both
3,10000022000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,...,Australia,0.0388,http://linked.data.gov.au/dataset/asgsed3/MB/1...,2641,2641,AUS,Australia,0.0388,http://linked.data.gov.au/dataset/asgsed3/MB/1...,both
4,10000023000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,...,Australia,0.0254,http://linked.data.gov.au/dataset/asgsed3/MB/1...,2641,2641,AUS,Australia,0.0254,http://linked.data.gov.au/dataset/asgsed3/MB/1...,both

In [9]:
mb_poa_merged = mb_poa_merged.drop(columns=[
    'MB_CATEGORY_2021', 'CHANGE_FLAG_2021', 'CHANGE_LABEL_2021',
    'SA1_CODE_2021',
    'SA3_CODE_2021', 'SA3_NAME_2021',
    'SA4_CODE_2021', 'SA4_NAME_2021',
    'GCCSA_CODE_2021', 'GCCSA_NAME_2021',
    'STATE_CODE_2021', 'STATE_NAME_2021',
    'AUS_CODE_2021_x', 'AUS_NAME_2021_x', 'AREA_ALBERS_SQKM_x', 'ASGS_LOCI_URI_2021_x',
    'AUS_CODE_2021_y', 'AUS_NAME_2021_y', 'AREA_ALBERS_SQKM_y', 'ASGS_LOCI_URI_2021_y',
    '_merge',
])

mb_poa_merged.head()

,MB_CODE_2021,SA2_CODE_2021,SA2_NAME_2021,POA_CODE_2021,POA_NAME_2021
0,10000009499,199999499,No usual address (NSW),9494,No usual address (Aust.)
1,10000010000,109011172,Albury - East,2640,2640
2,10000021000,109011176,Lavington,2641,2641
3,10000022000,109011176,Lavington,2641,2641
4,10000023000,109011176,Lavington,2641,2641

In [10]:
# Making sure that the MB_CODE_2021, POA_CODE_2021 and SA2_CODE_2021 are strictly stored as string data types 
# instead of integers. This prevents future issues in reading the files 
mb_poa_merged['MB_CODE_2021'] = mb_poa_merged['MB_CODE_2021'].astype(str)
mb_poa_merged['SA2_CODE_2021'] = mb_poa_merged['SA2_CODE_2021'].astype(str)
mb_poa_merged['POA_CODE_2021'] = mb_poa_merged['POA_CODE_2021'].astype(str)

# save the cleaned MB and POA merged dataset to be reused in the next step 
mb_poa_merged.to_parquet(f"{abs_output_dir}/mb_poa_merged.parquet", index=False)

26/09/18 22:02:45 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 922236 ms exceeds timeout 120000 ms
26/09/18 22:02:45 WARN SparkContext: Killing executors is not supported by current scheduler.
26/09/18 22:02:48 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:85)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:707)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1552)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:484)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1963)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:34)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:707)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:706)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:746)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@macbookpro.lan:65170
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:517)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/09/18 22:02:48 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:34)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:707)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:706)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:746)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@macbookpro.lan:65170
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:517)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/09/18 22:04:24 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:34)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:707)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:706)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:746)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@macbookpro.lan:65170
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:517)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/09/18 22:04:24 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:85)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:707)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1552)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:484)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1963)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)